---
apiVersion: v1
kind: Service
metadata:
  name: pihole-web
spec:
  type: NodePort
  selector:
    app: pihole
  ports:
  - port: 80
    nodePort: 30007
    name: pihole-admin
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-dns
spec:
  type: NodePort
  selector:
    app: pihole
  ports:
  - port: 53
    nodePort: 53
    protocol: UDP
    name: pihole-admin
