---
apiVersion: v1
kind: Service
metadata:
  name: pihole-web
spec:
  type: LoadBalancer
  selector:
    app: pihole
  ports:
  - port: 8081
    targetPort: 80
    name: pihole-admin
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-dns
spec:
  type: LoadBalancer
  selector:
    app: pihole
  ports:
  - port: 53
    targetPort: 53
    protocol: UDP
    name: pihole-dns
